# spring.datasource.url=jdbc:postgresql://gmdb.c9obrjjgrrkn.us-east-1.rds.amazonaws.com:5432/gmdb
# spring.datasource.username=jensbernhart
# spring.datasource.password=jensbernhart
# #Daten sind unverschlüsselt im Projekt gespeichert, welches public in github ist

# # spring.datasource.initialization-mode=always
# spring.jpa.database-platform = org.hibernate.dialect.PostgreSQLDialect
# spring.jpa.show-sql = true

# spring.jpa.hibernate.ddl-auto = create
# spring.datasource.sqlScriptEncoding=UTF-8
spring:
    profiles:
        active: development
---
spring:
    profiles: development
    jpa:
        hibernate:
            ddl-auto: create
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        database: POSTGRESQL
        generate-ddl: true
    datasource:
        url: jdbc:postgresql://gmdb.c9obrjjgrrkn.us-east-1.rds.amazonaws.com:5432/gmdb
        username: jensbernhart
        password: jensbernhart
        sql-script-encoding: UTF-8
---
spring:
    profiles: test
    jpa:
        show_sql: true
        database: H2
    datasource:
        url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
